# SPDX-FileCopyrightText: 2022 SAP SE or an SAP affiliate company and CLA-assistant contributors
#
# SPDX-License-Identifier: Apache-2.0

languages:
  Ruby: true
  JavaScript: true
  PHP: true
  Python: true
exclude_paths:
- src/client/assets/js/edge.5.0.1.min.js
- src/tests/**/*
