version: '3.7'

services:
  portal:
    image: cla-assistant
    build: .
    ports:
      - "5000:5000"
    networks:
      - cla
    env_file:
      - .env
    environment:
      MONGODB: mongodb://cla-db:27017/cla_assistant
      POSTGRES_USER: portal
      POSTGRES_PASSWORD: latrop
    depends_on:
      - cla-db

  cla-db:
    image: mongo
    networks:
      - cla


networks:
  cla:
