name: Deploy

on:
  push:
    branches:
    - master
    - release
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix: 
        node_version: 
        - 12
        
        os: 
        - ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node version 12.6
      uses: actions/setup-node@v1
      with:
        version:  ${{ matrix.node_version }}
    - name: build the docker image
      run: docker build .
        
        
        



