name: Node CI

on:
  push:
    branches:
    - master
    - release
    - release_green
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix: 
        node_version: 
        - 12
        
        os: 
        - ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node version 12.6
      uses: actions/setup-node@v1
      with:
        version:  ${{ matrix.node_version }}
    - name: Bower Install
      run: bower install
    - name: Npm Install
      run: npm install
    - name: grunt build and test
      run: |
        grunt build
        grunt test
        grunt coverage
    - name: Test Coverage
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        path-to-lcov: ./output/coverage/lcov.info
    - name: build and publish to dockerhub
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: sapclaassistant/claassistant
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        snapshot: true
    - name: Setup Google Cloud
      uses: actions/gcloud/auth@master
      env:
        GCLOUD_AUTH: ${{ secrets.GCP_PASSWORD }}
    - name: build and publish to gcp 
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
       name: eu.gcr.io/sap-cla-assistant/cla-assistant
       username: _json_key
       password: ${{ secrets.GCP_PASSWORD }}
       registry: eu.gcr.io
       snapshot: true
       
       
    deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: buildAndPushImage
    steps:
      - name: Setup Google Cloud
        uses: actions/gcloud/auth@master
        env:
          GCLOUD_AUTH: ${{ secrets.GCP_PASSWORD  }}
      - name: Deploy Cloud Run Service
        uses: actions/gcloud/cli@master
        with:
          entrypoint: sh
          args: -c "gcloud components install beta && gcloud components update && gcloud --quiet --project sap-cla-assistant beta run deploy contrast --image gcr.io/sap-cla-assistant/cla-assistant:latest"
        
        
        



