name: Deploy

on:
  push:
    branches:
    - master
    - release
    - release-green
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix: 
        node_version: 
        - 12
        
        os: 
        - ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node version 12.6
      uses: actions/setup-node@v1
      with:
        version:  ${{ matrix.node_version }}
    - name: build the docker image
      run: docker build -t eu.gcr.io/sap-cla-assistant/cla-assistant:latest -t sapclaassistant/claassistant:latest .
    - name: push the image to dockerHub
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push
        
        
        



