name: Deploy

on:
  push:
    branches:
    - master
    - release
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix: 
        node_version: 
        - 12
        
        os: 
        - ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node version 12.6
      uses: actions/setup-node@v1
      with:
        version:  ${{ matrix.node_version }}
    - name: build the docker image
      run: docker build -t eu.gcr.io/sap-cla-assistant/cla-assistant:latest -t sapclaassistant/claassistant:${GITHUB_SHA} .
    - name: push image to dockerhub
      run: | 
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push sapclaassistant/claassistant
    - name: setup google cloud platform 
      uses: actions/gcloud/auth@master
      env:
        GCLOUD_AUTH: ${{ secrets.GCP_base64 }}
    - name: push image to gcp
      uses: actions/gcloud/cli@master
      with:
        args: -c "docker push eu.gcr.io/sap-cla-assistant/cla-assistant"
      
        
        
        



