name: Node CI

on:
  push:
    branches:
    - master
    - release
    - release_green
  pull_request:
    branches:
    - master
    - release
    - release_green

jobs:
  build:
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix: 
        node_version: 
        - 12.6
        
        os: 
        - ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Use Node version 12.6
      uses: actions/setup-node@v1
      with:
        version:  ${{ matrix.node_version }}
    - name: Bower Install
      run: bower install
    - name: Npm Install
      run: npm install
    - name: grunt build and test
      run: |
        grunt build
        grunt test
        grunt coverage
    - name: Test Coverage
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        path-to-lcov: ./output/coverage/lcov.info



