name: Node CI

on:
  push:
    branches:
    - master
    - release

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 12.6
      uses: actions/setup-node@v1
      with:
        version: 12.6
    - name: Bower
      run: bower install
    - name: Install
      run: npm install
    - name: Test
      run: npm test
    - name: grunt build
      run: |
        grunt uglify
        grunt mocha_istanbul
    - name: Test Coverage
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        path-to-lcov: ./output/coverage/lcov.info



