name: Deploy

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix: 
        node_version: 
        - 12
        
        os: 
        - ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node version 12.6
      uses: actions/setup-node@v1
      with:
        version:  ${{ matrix.node_version }}
    - name: Bower Install
      run: bower install
    - name: Npm Install
      run: npm install
    - name: grunt build and test
      run: |
        grunt build
        grunt test
        grunt coverage
    - name: Test Coverage
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        path-to-lcov: ./output/coverage/lcov.info
    - name: rebase release branch from master
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git checkout release
        git rebase master
        git push origin release
        git checkout master
    - name: run hello world
      run: echo akshay is good
    - name: build the docker image
      run: docker build -t eu.gcr.io/sap-cla-assistant/cla-assistant:latest -t eu.gcr.io/sap-cla-assistant/cla-assistant:${GITHUB_SHA} -t sapclaassistant/claassistant:${GITHUB_SHA} .
    - name: push image to dockerhub
      run: | 
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push sapclaassistant/claassistant
    - name: setup google cloud platform 
      uses: actions/gcloud/auth@master
      env:
        GCLOUD_AUTH: ${{ secrets.GCP_base64 }}
    - name: setup Credential helper for gcp
      uses: actions/gcloud/cli@master
      with:
        args: auth configure-docker --quiet
    - name: push image to gcp
      uses: actions/gcloud/cli@master
      with:
        entrypoint: sh
        args: -c "docker push eu.gcr.io/sap-cla-assistant/cla-assistant"
    - name: deploy cloud run service
      uses: actions/gcloud/cli@master
      with:
        entrypoint: sh
        args: -c "gcloud components install beta && gcloud components update && gcloud --quiet --project sap-cla-assistant beta run deploy cla-assistant --platform managed --region us-central1 --image eu.gcr.io/sap-cla-assistant/cla-assistant:latest "

        

  
        
      
        
        
        



